### ISSUE TITLE
The source code is not being compiled. Am I doing it wrong?

### ISSUE THREAD

**Issue by TerabyteForever** [ferhatgec/whereismypointer#1]
![compileerror](https://user-images.githubusercontent.com/54219476/89718114-2e7dc300-d9c5-11ea-8c1d-03f4fb039644.png)
I got these errors when I try to compile the code. Am I doing it wrong, or is it an issue that is related to the code?

**Comment by ferhatgec** [comment]
I think you don't use library linker.
* Use ```sh make.sh``` or ```fscrift make``` in whereismypointer path.
* Otherwise, ```gcc -std=c99 WhereIsMyPointer.c -o wimpointer -lX11 && ./wimpointer ```

Tip: Use ```git clone <repository>``` 

If this is compiled, you should give a star and watch.
